### PR TITLE
Update pipedev and docs

### PR DESCRIPTION
**Pull request by mlaszloffy**

### CODE REVIEW

**Comment by mlaszloffy** [comment]
retest this please

**Comment by mlaszloffy** [comment]
retest this please

**Comment by mlaszloffy** [comment]
retest this please

**Comment by mlaszloffy** [comment]
retest this please

**Comment by mlaszloffy** [comment]
retest this please

**Review by pruzanov — APPROVED** [review]

**Review by xuemeiluo — APPROVED** [review]

**Pull request merged**
